FROM ghcr.io/ndscm/seed-office-stuff-container:latest

COPY ./openid_issuers.json /opt/stuff/openid_issuers.json

CMD [ \
  "--port", "8080", \
  "--trust_openid_issuers_file", "/opt/stuff/openid_issuers.json", \
  "--stuff_database", "postgres:///stuff_prod?host=/cloudsql/ndscm-prod:us-west1:ndscm-cloudsql-prod&sslmode=disable", \
  "--stuff_database_login", "stuff_prod", \
  "--stuff_database_secret_file", "/etc/secret/STUFF_DATABASE_SECRET/latest", \
  "--verbose" \
  ]
