FROM ghcr.io/ndscm/seed-cloud-sfe-container:latest

CMD [ \
  "--http_port", "8080", \
  "--session_id_cookie_name", "SFESID", \
  "--session_provider", "sql", \
  "--sqlsession_database", "postgres:///sfe_prod?host=/cloudsql/ndscm-prod:us-west1:ndscm-cloudsql-prod&sslmode=disable", \
  "--sqlsession_database_login", "sfe_prod", \
  "--sqlsession_database_secret_file", "/etc/secret/SFE_DATABASE_SECRET/latest", \
  "--openid_discovery_url", "https://account.ndscm.com/realms/ndscm/.well-known/openid-configuration", \
  "--sfe_openid_client_id", "sfe-prod", \
  "--sfe_openid_client_secret_file", "/run/secrets/SFE_OPENID_CLIENT_SECRET/latest", \
  "--sfe_openid_client_private_key_file", "/run/secrets/SFE_OPENID_CLIENT_PRIVATE_KEY/latest.pem", \
  "--golink_openid_client_id", "golink-sfe-prod", \
  "--golink_service_server", "https://seed-devprod-golink-prod-58770640413.us-west1.run.app", \
  "--kurisu_openid_discovery_url", "https://account.ndscm.com/realms/ndscm/.well-known/openid-configuration", \
  "--kurisu_openid_client_id", "kurisu-prod", \
  "--kurisu_openid_client_secret_file", "/run/secrets/KURISU_OPENID_CLIENT_SECRET/latest", \
  "--kurisu_service_server", "https://seed-newtype-kurisu-prod-58770640413.us-west1.run.app", \
  "--stuff_service_server", "https://seed-office-stuff-prod-58770640413.us-west1.run.app", \
  "--stuff_openid_client_id", "stuff-sfe-prod", \
  "--verbose" \
  ]
