services:
  golink:
    container_name: "golink"
    # See bug: https://github.com/tailscale/golink/issues/144
    image: "ghcr.io/tailscale/golink@sha256:f3a81bf7dcc56b8837db2de745d105888a144be457fe20108c253bc1f702bdd4"
    volumes:
      - /mnt/data/golink:/home/nonroot
    networks:
      - mbiz
    ports:
      - 6846:6846/tcp
    command:
      [
        "--dev-listen",
        ":6846",
        "--sqlitedb",
        "/home/nonroot/golink.db",
        "--verbose",
      ]
    restart: unless-stopped

networks:
  mbiz:
    name: mbiz
    external: true
