"""
Theseed

The monorepo of Theseed

The include statements must not be consecutive, because buildifier and
`bazel mod tidy` fight over the empty lines between them.
"""

module(
    name = "theseed",
    version = "1.0",
)

# Android

## Android Command Line Tools

include("//seed/vendor/android/cmdline-tools:cmdline-tools.MODULE.bazel")

## Android SDK

include("//seed/vendor/android/sdk:sdk.MODULE.bazel")

# CC

include("//seed/vendor/cc:cc.MODULE.bazel")

## Abseil

include("//seed/vendor/abseil:abseil.MODULE.bazel")

## Boost

include("//seed/vendor/boost:boost.MODULE.bazel")

# Common

include("//seed/vendor/bazel:common.MODULE.bazel")

# Container

include("//seed/vendor/container:container.MODULE.bazel")

# Go

include("//seed/vendor/go:go.MODULE.bazel")

# Grpc

include("//seed/vendor/grpc:grpc.MODULE.bazel")

# Java

include("//seed/vendor/java:java.MODULE.bazel")

# JavaScript and TypeScript

include("//seed/vendor/ts:ts.MODULE.bazel")

# LLVM

include("//seed/vendor/llvm:llvm.MODULE.bazel")

# Proto

include("//seed/vendor/proto:proto.MODULE.bazel")

# Python

include("//seed/vendor/python:python.MODULE.bazel")

# Rust

include("//seed/vendor/rust:rust.MODULE.bazel")

# Shell

include("//seed/vendor/shell:shell.MODULE.bazel")

# Apps

## Bazel

include("//seed/vendor/bazel:bazel.MODULE.bazel")

## Hedronvision Bazel Compile Commands Extractor

include("//contrib/vendor/hedronvision/bazel-compile-commands-extractor:bazel-compile-commands-extractor.MODULE.bazel")

## Keycloak

include("//seed/vendor/keycloak:keycloak.MODULE.bazel")

## VS Code

include("//seed/vendor/vscode:vscode.MODULE.bazel")
