packages:
  - "seed/cloud/login/client/tsx/login-service-context"
  - "seed/cloud/login/proto"
  - "seed/devprod/buildinfo/ts"
  - "seed/devprod/format/prettier"
  - "seed/devprod/golink/client/tsx/golink-service-context"
  - "seed/devprod/golink/proto"
  - "seed/devprod/golink/webapp"
  - "seed/devprod/gotcha/tsx"
  - "seed/devprod/ts/tool/verify-pnpm-lock"
  - "seed/newtype/playwright/proxy"
  - "seed/office/stuff/client/tsx/stuff-service-context"
  - "seed/office/stuff/proto"
  - "seed/office/stuff/webapp"
allowBuilds:
  "@ariga/atlas": true
  "@swc/core": true
  esbuild: true
  protobufjs: true
