#!/usr/bin/env bash
set -eux
set -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../../../.."

if [[ ",${maintain_scopes}," == *",user,"* ]]; then
    printf "\e[34m[user] Checking seed managed profile...\e[0m\n"

    if [[ "${oslike}" == "debian" || "${oslike}" == "darwin" ]]; then
        mkdir -m 0700 -p ${HOME}/.local
        mkdir -m 0700 -p ${HOME}/.local/bin
        mkdir -m 0700 -p ${HOME}/.local/lib
        cat <<EOF >${HOME}/.managed_profile.tmp
# Seed Managed Profile

# This file is generated by seed/devprod/smd/workstation/maintain.sh.
# Do not edit this file directly.

## User

export ND_USER_HANDLE="${ND_USER_HANDLE}"
export ND_USER_DOMAIN="${ND_USER_DOMAIN}"
export ND_USER_EMAIL="${ND_USER_HANDLE}@${ND_USER_DOMAIN}"
export ND_USER_DISPLAY_NAME="${ND_USER_DISPLAY_NAME}"

## Path

case ":\${PATH}:" in
*:/usr/local/bin:*) ;;
*) export PATH="/usr/local/bin:\${PATH}" ;;
esac

case ":\${PATH}:" in
*:\${HOME}/.local/bin:*) ;;
*) export PATH="\${HOME}/.local/bin:\${PATH}" ;;
esac

case ":\${PATH}:" in
*:\${HOME}/bin:*) ;;
*) export PATH="\${HOME}/bin:\${PATH}" ;;
esac

## Editor

export EDITOR="vim"
EOF
        cat <<EOF >${HOME}/.managed_shrc.tmp
# Seed Managed Shell Run Commands

# This file is generated by seed/devprod/smd/workstation/maintain.sh.
# Do not edit this file directly.

source "\${HOME}/.managed_profile"

## User

function me {
  printf "\${ND_USER_HANDLE}"
}
EOF
        if ! grep -F -q -s -x 'source $HOME/.managed_profile' "${HOME}/.profile"; then
            printf '\nsource $HOME/.managed_profile\n' >>"${HOME}/.profile"
        fi
        if ! grep -F -q -s -x 'source $HOME/.managed_profile' "${HOME}/.bash_profile"; then
            printf '\nsource $HOME/.managed_profile\n' >>"${HOME}/.bash_profile"
        fi
        if ! grep -F -q -s -x 'source $HOME/.managed_profile' "${HOME}/.zprofile"; then
            printf '\nsource $HOME/.managed_profile\n' >>"${HOME}/.zprofile"
        fi
        if ! grep -F -q -s -x 'source $HOME/.managed_shrc' "${HOME}/.bashrc"; then
            printf '\nsource $HOME/.managed_shrc\n' >>"${HOME}/.bashrc"
        fi
        if ! grep -F -q -s -x 'source $HOME/.managed_shrc' "${HOME}/.zshrc"; then
            printf '\nsource $HOME/.managed_shrc\n' >>"${HOME}/.zshrc"
        fi
    fi

    if [[ "${oslike}" == "debian" ]]; then
        if ${wsl}; then
            cat <<EOF >>"${HOME}/.managed_profile.tmp"

## WSL

export WINDOWS_HOST="\$(ip route show | grep -i default | awk '{ print \$3 }')"
alias open="wslview"
EOF
        fi
    fi

    printf "\e[32m[user] Check seed managed profile done.\e[0m\n"
fi
