FROM docker.io/library/debian:trixie

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt update
RUN apt install -y ca-certificates
RUN apt install -y curl
RUN apt install -y iputils-ping
