FROM docker.io/library/debian:trixie

RUN sed -i 's,http://deb.debian.org/,http://mirrors.tuna.tsinghua.edu.cn/,g' /etc/apt/sources.list.d/debian.sources

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y ca-certificates
RUN apt install -y curl
RUN apt install -y iputils-ping
