"""Repository rules that build an offline apt mirror from a deb822 sources file.

apt_dists downloads the signed InRelease and compressed Packages indices into a
real dists/ tree; apt_pool resolves a package closure and downloads the .debs
into a pool/ tree. A Containerfile points apt at the result via file://, and apt
still verifies the InRelease signature and Packages hashes.

Index fetching follows rules_distroless's `deb_resolve` (`_fetch_package_index`
in apt/private/apt_deb_repository.bzl), but keeps the metadata as output rather
than discarding it after computing a lockfile.

Both rules take an optional `lock` attribute: a JSON file mapping each URL to a
`{"integrity": <SRI>}` object. When set, downloads are verified against it and a
`:lock` target regenerates it from the fetch (`bazel run @repo//:lock`).
"""

def _apparent_name(rctx):
    """The apparent repo name (last segment of the canonical rctx.name)."""
    return rctx.name.rsplit("+", 1)[-1].rsplit("~", 1)[-1]

def _download(rctx, urls, rel, output, locked, computed):
    """Downloads the first of `urls` that serves `rel`, returning success.

    `locked` and `computed` map a URL to a `{"integrity": <SRI>}` entry. A URL in
    `locked` is verified against its integrity (a mismatch counts as a failed
    download, so the caller falls back to the next URL). The integrity of whatever
    was fetched is recorded in `computed` for regenerating the lockfile.
    """
    for url in urls:
        base = url.rstrip("/")
        final_url = "{}/{}".format(base, rel)
        result = rctx.download(
            url = final_url,
            output = output,
            integrity = locked.get(final_url, {}).get("integrity", ""),
            allow_fail = True,
        )
        if result.success:
            computed[final_url] = {"integrity": result.integrity}
            return True
    return False

# Network downloads make the output depend on what the mirror serves at fetch
# time. The optional `lock` attribute pins it: a JSON file mapping each URL to a
# `{"integrity": <SRI>}` object. Downloads are verified against it (see
# `_download`), and a generated `:lock` target regenerates it from the fetch.

# Set this to make a fetch ignore the existing lockfile and record fresh
# integrities instead of verifying against them. Use it to re-lock a URL whose
# upstream content changed: `APT_LOCK_UPDATE=1 bazel run @repo//:lock`.
_LOCK_UPDATE_ENV = "APT_LOCK_UPDATE"

def _lock_update_requested(rctx):
    return rctx.getenv(_LOCK_UPDATE_ENV, "") not in ("", "0")

def _load_lock(rctx):
    """Reads the lock attribute into a {url: {"integrity": ...}} dict (empty if unset/blank)."""
    if not rctx.attr.lock:
        return {}
    text = rctx.read(rctx.path(rctx.attr.lock)).strip()
    if not text:
        return {}
    return json.decode(text)

def _format_lock(computed):
    """Renders `computed` as stable, pretty-printed JSON (sorted by URL)."""
    if not computed:
        return "{}"
    lines = [
        "    {}: {}".format(json.encode(url), json.encode(computed[url]))
        for url in sorted(computed)
    ]
    return "{\n" + ",\n".join(lines) + "\n}"

_UPDATE_LOCK_SH = """#!/usr/bin/env bash
# Generated by //seed/devprod/container/starlark:apt.bzl. Writes the lockfile from
# the integrities computed during the last fetch. Adding packages/suites re-locks
# with a plain `bazel run`; set {env}=1 to re-lock changed upstream URLs.
set -euo pipefail

dest="${{BUILD_WORKSPACE_DIRECTORY}}/{dest}"
cat >"${{dest}}" <<'APT_LOCK_EOF'
{content}
APT_LOCK_EOF
echo "Wrote ${{dest}}"
"""

def _apt_mirror_repo(rctx, dirname, computed):
    """Writes the repo's BUILD.bazel, plus a `:lock` target when locked.

    The BUILD holds a filegroup over `dirname` named after the repo, so callers
    can use the `@repo` shorthand. A locked repo also gets a `:lock` sh_binary
    that rewrites the lockfile.
    """
    repo_name = _apparent_name(rctx)
    build = (
        "filegroup(\n" +
        "    name = \"%s\",\n" % repo_name +
        "    srcs = [\"%s\"],\n" % dirname +
        "    visibility = [\"//visibility:public\"],\n" +
        ")\n"
    )

    if rctx.attr.lock:
        lock = rctx.attr.lock
        dest = "{}/{}".format(lock.package, lock.name)
        rctx.file(
            "update-lock.sh",
            _UPDATE_LOCK_SH.format(
                env = _LOCK_UPDATE_ENV,
                dest = dest,
                content = _format_lock(computed),
            ),
            executable = True,
        )
        build = (
            "load(\"@rules_shell//shell:sh_binary.bzl\", \"sh_binary\")\n\n" +
            build +
            "\nsh_binary(\n" +
            "    name = \"lock\",\n" +
            "    srcs = [\"update-lock.sh\"],\n" +
            "    visibility = [\"//visibility:public\"],\n" +
            ")\n"
        )

    rctx.file("BUILD.bazel", build)

def _tokens(value):
    """Splits a deb822 field on whitespace (Starlark split needs a separator)."""
    return [tok for tok in value.replace("\t", " ").split(" ") if tok]

def _parse_sources(content):
    """Parses deb822 stanzas into a list of {field: value} dicts."""
    stanzas = []
    fields = {}
    for line in content.split("\n"):
        if line.strip() == "":
            if fields:
                stanzas.append(fields)
                fields = {}
            continue
        if line.lstrip().startswith("#"):
            continue

        # Folded continuation lines start with whitespace; no field we read is
        # multi-line, so skip them.
        if line[0] == " " or line[0] == "\t":
            continue

        key, sep, value = line.partition(":")
        if not sep:
            continue
        fields[key.strip()] = value.strip()

    if fields:
        stanzas.append(fields)
    return stanzas

# --- apt_dists ----------------------------------------------------------------
#
# For each suite in the sources file, apt_dists downloads the signed InRelease
# and the compressed Packages index (per component/arch) into a real dists/ tree.
# That's the offline metadata half of the mirror, which apt verifies via file://.

# Packages compression variants to try, most-preferred first. apt needs only one
# present, as long as it matches a hash in InRelease.
_PACKAGES_EXTS = [".xz", ".gz", ""]

def _apt_dists_impl(rctx):
    content = rctx.read(rctx.path(rctx.attr.sources))

    # In update mode, ignore the existing lock and record fresh integrities.
    locked = {} if _lock_update_requested(rctx) else _load_lock(rctx)
    computed = {}

    outputs = []
    for stanza in _parse_sources(content):
        if "deb" not in _tokens(stanza.get("Types", "deb")):
            continue

        urls = _tokens(stanza["URIs"])
        suites = _tokens(stanza["Suites"])
        comps = _tokens(stanza.get("Components", ""))

        for suite in suites:
            # InRelease is signed and covers the whole suite.
            inrelease = "dists/{}/InRelease".format(suite)
            if not _download(rctx, urls, inrelease, inrelease, locked, computed):
                fail("Failed to download {} from any of {}".format(inrelease, urls))
            outputs.append(inrelease)

            for comp in comps:
                for arch in rctx.attr.archs:
                    got = None
                    for ext in _PACKAGES_EXTS:
                        rel = "dists/{}/{}/binary-{}/Packages{}".format(suite, comp, arch, ext)
                        if _download(rctx, urls, rel, rel, locked, computed):
                            got = rel
                            break
                    if not got:
                        fail("Failed to download a Packages index for {}/{}/{} from any of {}".format(suite, comp, arch, urls))
                    outputs.append(got)

    # Expose the whole dists/ tree as a single directory artifact.
    _apt_mirror_repo(rctx, "dists", computed)

apt_dists = repository_rule(
    implementation = _apt_dists_impl,
    attrs = {
        "sources": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "A Debian deb822 `.sources` file (e.g. debian.sources).",
        ),
        "archs": attr.string_list(
            default = ["amd64"],
            doc = "Binary architectures to fetch Packages indices for.",
        ),
        "lock": attr.label(
            allow_single_file = True,
            doc = "Optional JSON lockfile mapping each download URL to a " +
                  "`{\"integrity\": <SRI>}` object. Downloads are verified " +
                  "against it; a `:lock` target regenerates it.",
        ),
    },
    environ = [_LOCK_UPDATE_ENV],
    doc = "Mirrors the InRelease + Packages.xz metadata for a deb822 sources file.",
)

# --- apt_pool -----------------------------------------------------------------
#
# Given the metadata mirror and a set of root packages, apt_pool resolves the
# full install closure over Pre-Depends + Depends + Recommends (matching apt's
# default "install recommends" behavior) and downloads every .deb into a real
# pool/ layout. With the dists/ tree, that's a self-contained offline mirror.

def _dep_names(value):
    """Parses a Depends/Recommends/Provides field into a list of OR-groups.

    Each group is the bare alternative package names, with version relations,
    architecture restrictions and multiarch `:` qualifiers stripped.
    """
    groups = []
    for group in value.split(","):
        alts = []
        for alt in group.split("|"):
            name = alt.strip()
            for sep in ["(", "[", ":", " "]:
                name = name.split(sep)[0]
            name = name.strip()
            if name:
                alts.append(name)
        if alts:
            groups.append(alts)
    return groups

def _real_names(name, index, provides):
    """Resolves a (possibly virtual) dependency name to real package names."""
    if name in index:
        return [name]
    if name in provides:
        # apt would pick one provider; the first is a good-enough default.
        return [provides[name][0]]
    return []

def _read_packages(rctx, dists_dir, suite, comp, arch):
    """Reads (and decompresses) a Packages index from the apt_dists mirror."""
    binary = dists_dir.get_child(suite).get_child(comp).get_child("binary-" + arch)
    for (ext, cmd) in [(".xz", ["xz", "-dc"]), (".gz", ["gzip", "-dc"]), ("", None)]:
        path = binary.get_child("Packages" + ext)
        if not path.exists:
            continue
        if cmd == None:
            return rctx.read(path)
        result = rctx.execute(cmd + [str(path)])
        if result.return_code != 0:
            fail("Failed to decompress {}:\n{}".format(path, result.stderr))
        return result.stdout
    fail("No Packages index found for {}/{}/binary-{} under {}".format(suite, comp, arch, dists_dir))

def _parse_packages(content, base_url, index, provides):
    """Parses a Packages index, filling `index` (name -> [pkg]) and `provides`."""
    for stanza in content.split("\n\n"):
        if stanza.strip() == "":
            continue

        f = {}
        for line in stanza.split("\n"):
            # Folded continuation lines start with whitespace; every field we
            # read is single-line, so skip them.
            if line == "" or line[0] == " " or line[0] == "\t":
                continue
            key, sep, value = line.partition(":")
            if sep:
                f[key.strip()] = value.strip()

        if "Package" not in f or "Filename" not in f:
            continue

        name = f["Package"]
        pkg = {
            "name": name,
            "filename": f["Filename"],
            "base_url": base_url,
            "deps": _dep_names(f.get("Pre-Depends", "")) +
                    _dep_names(f.get("Depends", "")) +
                    _dep_names(f.get("Recommends", "")),
        }
        if name not in index:
            index[name] = []
        index[name].append(pkg)

        for group in _dep_names(f.get("Provides", "")):
            for virtual in group:
                if virtual not in provides:
                    provides[virtual] = []
                provides[virtual].append(name)

def _resolve_closure(index, provides, roots):
    """Returns the set of real package names reachable from `roots`."""
    visited = {}
    queue = list(roots)

    # Starlark has no `while`; bound the walk generously and break when drained.
    for _ in range(1000000):
        if not queue:
            break
        name = queue.pop()
        for real in _real_names(name, index, provides):
            if real in visited:
                continue
            visited[real] = True

            # A package may appear in several suites with different deps; union
            # them so nothing is missed.
            for pkg in index[real]:
                for group in pkg["deps"]:
                    for alt in group:
                        if _real_names(alt, index, provides):
                            queue.append(alt)
                            break

    return visited.keys()

def _apt_pool_impl(rctx):
    # rctx.path on the filegroup resolves to <repo_root>/<target_name>; the
    # metadata tree lives at <repo_root>/dists next to it.
    dists_dir = rctx.path(rctx.attr.dists).dirname.get_child("dists")

    # In update mode, ignore the existing lock and record fresh integrities.
    locked = {} if _lock_update_requested(rctx) else _load_lock(rctx)
    computed = {}

    index = {}
    provides = {}
    for stanza in _parse_sources(rctx.read(rctx.path(rctx.attr.sources))):
        if "deb" not in _tokens(stanza.get("Types", "deb")):
            continue

        base_url = _tokens(stanza["URIs"])[0].rstrip("/")
        if base_url.startswith("http://"):
            base_url = "https://" + base_url[len("http://"):]

        for suite in _tokens(stanza["Suites"]):
            for comp in _tokens(stanza.get("Components", "")):
                for arch in rctx.attr.archs:
                    content = _read_packages(rctx, dists_dir, suite, comp, arch)
                    _parse_packages(content, base_url, index, provides)

    # Download every version of every package in the closure. Grabbing all
    # versions sidesteps Debian version comparison and guarantees whichever one
    # apt selects is present.
    seen = {}
    for name in _resolve_closure(index, provides, rctx.attr.packages):
        for pkg in index[name]:
            filename = pkg["filename"]
            if filename in seen:
                continue
            seen[filename] = True

            # Filename is relative to the archive root and starts with "pool/",
            # so it doubles as the on-disk mirror path.
            if not _download(rctx, [pkg["base_url"]], filename, filename, locked, computed):
                fail("Failed to download {} from {}".format(filename, pkg["base_url"]))

    _apt_mirror_repo(rctx, "pool", computed)

apt_pool = repository_rule(
    implementation = _apt_pool_impl,
    attrs = {
        "sources": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The same deb822 `.sources` file passed to apt_dists.",
        ),
        "dists": attr.label(
            mandatory = True,
            doc = "An apt_dists repo providing the dists/ metadata tree.",
        ),
        "packages": attr.string_list(
            mandatory = True,
            doc = "Root packages to resolve; their Depends + Recommends closure " +
                  "is downloaded into pool/.",
        ),
        "archs": attr.string_list(
            default = ["amd64"],
            doc = "Binary architectures to resolve and download.",
        ),
        "lock": attr.label(
            allow_single_file = True,
            doc = "Optional JSON lockfile mapping each .deb URL to a " +
                  "`{\"integrity\": <SRI>}` object. Downloads are verified " +
                  "against it; a `:lock` target regenerates it.",
        ),
    },
    environ = [_LOCK_UPDATE_ENV],
    doc = "Downloads the Depends+Recommends closure of `packages` into a pool/ tree.",
)

# --- apt_mirror ---------------------------------------------------------------
#
# Bundles the dists/ tree, the pool/ tree and the use.sh/restore.sh scripts into
# one self-contained mirror/ directory, plus a deb822 source pointing at
# file:///apt/mirror. A Containerfile COPYs it to /apt/mirror and runs use.sh to
# install offline (restore.sh to revert). A regular rule, not a repo rule.

def _apt_mirror_impl(ctx):
    out = ctx.actions.declare_directory("mirror")
    ctx.actions.run_shell(
        outputs = [out],
        inputs = [
            ctx.file.dists,
            ctx.file.pool,
            ctx.file.sources,
            ctx.file._use,
            ctx.file._restore,
        ],
        command = """
set -eu
mkdir -p "{out}/dists" "{out}/pool" "{out}/sources.list.d"
cp -RL "{dists}/." "{out}/dists/"
cp -RL "{pool}/." "{out}/pool/"
sed 's|^URIs:.*|URIs: file:///apt/mirror|' "{sources}" >"{out}/sources.list.d/debian.sources"
install -m 0755 "{use}" "{out}/use.sh"
install -m 0755 "{restore}" "{out}/restore.sh"
""".format(
            out = out.path,
            dists = ctx.file.dists.path,
            pool = ctx.file.pool.path,
            sources = ctx.file.sources.path,
            use = ctx.file._use.path,
            restore = ctx.file._restore.path,
        ),
        mnemonic = "AptMirror",
        progress_message = "Assembling apt mirror %s" % out.short_path,
    )
    return [DefaultInfo(files = depset([out]))]

apt_mirror = rule(
    implementation = _apt_mirror_impl,
    attrs = {
        "dists": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "An apt_dists repo providing the dists/ metadata tree.",
        ),
        "pool": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "An apt_pool repo providing the pool/ .deb tree.",
        ),
        "sources": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "deb822 sources whose URIs are rewritten to file:///apt/mirror.",
        ),
        "_use": attr.label(
            allow_single_file = True,
            default = "//seed/devprod/container/starlark:apt-mirror-use.sh",
        ),
        "_restore": attr.label(
            allow_single_file = True,
            default = "//seed/devprod/container/starlark:apt-mirror-restore.sh",
        ),
    },
    doc = "Bundles dists/, pool/ and the use/restore scripts into one mirror/ dir.",
)
