"""Host container-engine detection, performed at repo-fetch time.

`build_freedom_image` drives a real engine (podman), absent on CI and most
workstations. This repository rule probes PATH for it and records what it found,
so build_freedom_image can mark itself `target_compatible_with` an available
engine — letting Bazel skip it as "incompatible" instead of failing the build.
"""

# Engines build_freedom_image knows how to drive. Keep in sync with container.bzl
# (which fails for anything but podman).
_ENGINES = ["podman"]

def _engine_detect_impl(rctx):
    available = [engine for engine in _ENGINES if rctx.which(engine) != None]
    rctx.file("BUILD.bazel", "")
    rctx.file(
        "local.bzl",
        "# Generated by //seed/devprod/container/starlark:engine.bzl.\n" +
        "LOCAL_CONTAINER_ENGINES = {}\n".format(repr(available)),
    )

engine_detect = repository_rule(
    implementation = _engine_detect_impl,
    doc = "Probes PATH for a local container engine; exposes LOCAL_CONTAINER_ENGINES in local.bzl.",
    # local + environ re-runs the probe when PATH changes, so installing or
    # removing an engine is picked up instead of masked by a cached result.
    local = True,
    environ = ["PATH"],
)
