load("@rules_img//img:image.bzl", "image_manifest")
load("@rules_img//img:push.bzl", "image_push")

image_manifest(
    name = "prod",
    base = "//seed/newtype/kurisu/container",
    config_fragment = "prod.json",
)

image_push(
    name = "push-prod",
    image = ":prod",
    registry = "us-docker.pkg.dev",
    repository = "ndscm-prod/container-us/seed-newtype-kurisu-deploy-gcloud",
    tag = "prod",
)
