load("@rules_img//img:image.bzl", "image_manifest")
load("@rules_img//img:load.bzl", "image_load")

image_manifest(
    name = "prod",
    base = "//seed/newtype/kurisu/container",
    config_fragment = "prod.json",
    platform = "//seed/devprod/platform:linux-x64",
)

image_load(
    name = "load-prod",
    image = ":prod",
    tag = "us-docker.pkg.dev/ndscm-prod/container-us/seed-newtype-kurisu-deploy-gcloud:prod",
)
