FROM ghcr.io/ndscm/ubuntu:latest

RUN userdel --remove ubuntu || true

# System packages

RUN apt update
RUN apt install -y build-essential
RUN apt install -y curl
RUN apt install -y direnv
RUN apt install -y git
RUN apt install -y gnupg2
RUN apt install -y iproute2
RUN apt install -y iputils-ping
RUN apt install -y libcap2-bin
RUN apt install -y lsb-release
RUN apt install -y netcat-openbsd
RUN apt install -y rsync
RUN apt install -y ssh
RUN apt install -y systemd
RUN apt install -y systemd-sysv
RUN apt install -y vim
RUN apt install -y zsh

# Systemd configuration

RUN systemctl mask systemd-resolved-monitor.socket
RUN systemctl mask systemd-resolved-varlink.socket
RUN systemctl mask systemd-resolved.service

# Amadeus dependencies

RUN curl -fsSL "https://github.com/facebook/dotslash/releases/latest/download/dotslash-ubuntu-22.04.$(uname -m).tar.gz" \
  | tar fxz - -C /usr/local/bin --no-same-owner

COPY ./bin/. /usr/local/bin/.

COPY ./smd /opt/smd

COPY --chmod=0755 ./entrypoint.sh /entrypoint.sh

VOLUME /home

STOPSIGNAL SIGRTMIN+3
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "christina" ]
