// Dummy ConnectRPC package
//
// This package is used to make go mod happly about the connect package. Since
// the import of connect package is generated by protoc, without this package,
// go mod will identify it as indirect dependency and clean it with go mod
// tidy.

package dummy

import "connectrpc.com/connect"

const _ = connect.IsAtLeastVersion1_13_0
