# The official Debian image doesn't create a default user, unlike
# Ubuntu which claims uid 1000 for "ubuntu". We use Debian so
# uid 1000 is available for the Jenkins user.
ARG BASE_DEBIAN=ghcr.io/ndscm/debian:latest
FROM "${BASE_DEBIAN}" AS jenkins-agent
# Based on the upstream Jenkins agent Dockerfile:
# https://github.com/jenkinsci/docker-agents/blob/3355.v388858a_47b_33-20/debian/Dockerfile
ARG TARGETARCH

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

RUN groupadd -g "${gid}" "${group}"
RUN useradd -l -c "Jenkins user" -d /home/"${user}" -u "${uid}" -g "${gid}" -m "${user}" || echo "user ${user} already exists."

ENV LANG=C.UTF-8
ENV TZ=Etc/UTC

RUN apt update
RUN apt install -y ca-certificates
RUN apt install -y curl
RUN apt install -y fontconfig
RUN apt install -y git
RUN apt install -y less
RUN apt install -y netbase
RUN apt install -y openjdk-25-jdk
RUN apt install -y openssh-client
RUN apt install -y patch
RUN apt install -y tzdata

ARG JENKINS_INBOUND_AGENT_VERSION=latest-trixie-jdk25
COPY --from=docker.io/jenkins/inbound-agent:"${JENKINS_INBOUND_AGENT_VERSION}" /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar
RUN chown "${user}":"${group}" /usr/share/jenkins/agent.jar
RUN chmod 0644 /usr/share/jenkins/agent.jar
RUN ln -sf /usr/share/jenkins/agent.jar /usr/share/jenkins/slave.jar

ARG GIT_LFS_VERSION=3.7.1
RUN curl -L -s -o git-lfs.tgz "https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VERSION}/git-lfs-linux-${TARGETARCH}-v${GIT_LFS_VERSION}.tar.gz"
RUN mkdir -p /tmp/git-lfs
RUN tar xzf git-lfs.tgz -C /tmp/git-lfs --strip-components=1
RUN bash /tmp/git-lfs/install.sh
RUN git lfs install --skip-repo --system

COPY --from=docker.io/jenkins/inbound-agent:"${JENKINS_INBOUND_AGENT_VERSION}" /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
RUN ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

USER "${user}"
ENV AGENT_WORKDIR=/home/"${user}"/agent
RUN mkdir -p /home/"${user}"/.jenkins
RUN mkdir -p "${AGENT_WORKDIR}"

VOLUME /home/"${user}"/.jenkins
VOLUME "${AGENT_WORKDIR}"
WORKDIR /home/"${user}"
ENV USER=${user}

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]

FROM jenkins-agent AS seed-devprod-jenkins-node-container
ARG TARGETARCH

USER root

RUN apt update
RUN apt install -y build-essential
RUN apt install -y curl
RUN apt install -y direnv
RUN apt install -y gnupg2
RUN apt install -y iputils-ping
RUN apt install -y lsb-release
RUN apt install -y procps
RUN apt install -y rsync

RUN curl -fsSL "https://github.com/facebook/dotslash/releases/latest/download/dotslash-ubuntu-22.04.$(uname -m).tar.gz" | tar xzvf - -C /usr/local/bin

COPY ./bin/. /usr/local/bin/.

USER jenkins
