load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "openid-credential-helper_lib",
    srcs = ["main.go"],
    importpath = "github.com/ndscm/theseed/seed/cloud/login/tool/openid-credential-helper",
    visibility = ["//visibility:private"],
    deps = [
        "//seed/infra/auth/go/openid",
        "//seed/infra/error/go/seederr",
        "//seed/infra/flag/go/seedflag",
        "//seed/infra/init/go/seedinit",
        "//seed/infra/log/go/seedlog",
        "@org_golang_x_oauth2//:oauth2",
    ],
)

go_binary(
    name = "openid-credential-helper",
    embed = [":openid-credential-helper_lib"],
    visibility = ["//visibility:public"],
)
