pull = use_repo_rule("@rules_img//img:pull.bzl", "pull")

pull(
    name = "seed_devprod_container_ubuntu_2604",
    digest = "sha256:3131b4cc82a783df6c9df078f86e01819a13594b865c2cad47bd1bca2b7063bb",
    registry = "index.docker.io",
    repository = "library/ubuntu",
    tag = "26.04",
)

apt = use_extension("@rules_distroless//apt:extensions.bzl", "apt")
apt.install(
    name = "seed_devprod_container_ubuntu_2604_apt",
    lock = "//seed/devprod/container/ubuntu:apt.lock.json",
    manifest = "//seed/devprod/container/ubuntu:apt.yaml",
)
use_repo(apt, "seed_devprod_container_ubuntu_2604_apt")
