FROM docker.io/library/ubuntu:26.04

RUN sed -i 's,http://archive.ubuntu.com/ubuntu,http://mirrors.tuna.tsinghua.edu.cn/ubuntu,g' /etc/apt/sources.list.d/ubuntu.sources
RUN sed -i 's,http://security.ubuntu.com/ubuntu,http://mirrors.tuna.tsinghua.edu.cn/ubuntu,g' /etc/apt/sources.list.d/ubuntu.sources

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y ca-certificates
RUN apt install -y curl
RUN apt install -y iputils-ping
