FROM ghcr.io/ndscm/ubuntu:latest

# Install debug tools
RUN apt update
RUN apt install -y curl
RUN apt install -y gnupg2
RUN apt install -y lsb-release

COPY ./hooin-server /opt/hooin/hooin-server

RUN useradd --shell /bin/bash --create-home hooin
USER hooin
WORKDIR /home/hooin

ENTRYPOINT [ "/opt/hooin/hooin-server" ]

CMD [ "--verbose" ]
